# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

# PHP version used in first build configuration.
php:
  - "5.4"
  - "5.5"

# WordPress version used in first build configuration.
env:
  - WP_VERSION=master

# we will build a matrix of PHP to WP_VERSIONs later.
matrix:
  allow_failures:
  - php: hhvm

before_install:  
  # Selenium server
  - "sh -e /etc/init.d/xvfb start"
  - "export DISPLAY=:99.0"
  #- "wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar"
  #- "java -jar selenium-server-standalone-2.31.0.jar > /dev/null &"
  #- sleep 5

   # Create environmental variable from basename of starting directory.
  - export PLUGIN_SLUG=$(basename $(pwd))

install:
  # lets show where we start out
  - pwd 
  
  #run composer installs
  - composer install
  
  # install fontcongig
  - sudo apt-get install fontconfig
  
  # make symlink - WPCLI
  - sudo ln -s /home/travis/build/inboundnow/landing-pages/vendor/wp-cli/wp-cli/bin/wp /usr/bin/wp
  
  # make symlink - PhantomJs
  - sudo ln -s /home/travis/build/inboundnow/landing-pages/vendor/jakoch/phantomjs/phantomjs /usr/bin/phantomjs
 
  # make symlink - Codeception
  - sudo ln -s /home/travis/build/inboundnow/landing-pages/vendor/codeception/codeception/codecept /usr/bin/codecept
  
  # make symlink - WPBRowser
  #- sudo ln -s /home/travis/build/inboundnow/landing-pages/vendor/lucatume/wp-browser/wpcept /usr/bin/WPBrowser
  
  # install Apache
  - sudo apt-get update
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  
  # create hosts file for site
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/inboundtesting.dev
  
  # enable new hosts file
  - sudo a2ensite inboundtesting.dev 
  
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
      
  # restart apache & reload configuration files
  - sudo service apache2 restart 
  - sudo service apache2 reload 
  
  # install WordPress 
  - sudo mkdir /var/www/inboundtesting.dev/
  - sudo chown -R $USER:$USER /var/www/inboundtesting.dev
  - mysql -e "CREATE DATABASE inboundtesting;" -uroot
  - cd /var/www/inboundtesting.dev/
  - wp core download --locale=en_US
  - wp core config --dbname=inboundtesting --dbuser=root 
  - wp core install --url="http://inboundtesting.dev" --title="Inbound Now Unit Testing" --admin_user="admin" --admin_password="admin" --admin_email="tests@inboundnow.com" 
  
  # Install CTA (from master)
  - sudo git clone --branch="master" https://github.com/inboundnow/cta.git /var/www/inboundtesting.dev/wp-content/plugins/cta
  - wp plugin activate cta
  
  # Install Leads ( from git )
  - sudo git clone --branch="master" https://github.com/inboundnow/leads.git /var/www/inboundtesting.dev/wp-content/plugins/leads 
  - wp plugin activate leads
  
  # Install Landing Pages ( from travis build )
  - cp -r /home/travis/build/inboundnow/$PLUGIN_SLUG /var/www/inboundtesting.dev/wp-content/plugins/$PLUGIN_SLUG
  - wp plugin activate landing-pages
  
  # create blank htaccess file
  - sudo touch /var/www/inboundtesting.dev/.htaccess
  
  # Set permalinks 
  - wp rewrite structure '%postname%'
  - wp rewrite flush --hard
  
  # Set permissions for root website contents folder & all subfolders
  - sudo chmod -R 755 /var/www
  
  - cat /var/www/inboundtesting.dev/.htaccess 

before_script:


  # change into plugin directory to make sure our script runs the right tests
  - cd /var/www/inboundtesting.dev/wp-content/plugins/$PLUGIN_SLUG

  - ls tests
  - ls vendor
  

script:
  - phpunit
  - codecept run
  #- codecept run  --debug -vvv

addons:
  hosts:
    - inboundtesting.dev
  #sauce_connect:
   # username: "hudson-inbound"
   # access_key: "fad20a89-ba7c-4797-b2e2-a13309885479"